# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 526798375beb84ff1e80a08451564eb97f11013437e1dfcdb7a628ab83f72131187a08532462c0dbfb34bb44ca442e59ecaaf8a88344ec49bd47c47b00c6e12a

test:
  secret_key_base: 4bb715d2bcf2c6518f113359ab4693e95134c59efab28c4c5aafdc582112fad78f16ccf0e6a00c5d76ab34f56e7c17b8dd041d051836b58dde261b6d2fabcd88

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
